CREATE TABLE issue_conversation (
    id varchar(36) PRIMARY KEY,
    organization_id varchar(255) NOT NULL,
    repository varchar(255) NOT NULL,
    created_by varchar(200) NOT NULL,
    status varchar(24) NOT NULL,
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    started_at timestamptz,
    runner_id varchar(36),
    failure_summary varchar(500),
    draft_title varchar(200),
    draft_body text,
    draft_criteria text,
    provider varchar(80),
    model varchar(200),
    input_tokens bigint NOT NULL DEFAULT 0,
    output_tokens bigint NOT NULL DEFAULT 0,
    estimated_cost_micros bigint NOT NULL DEFAULT 0,
    cost_known boolean NOT NULL DEFAULT false,
    issue_number integer,
    issue_url varchar(500)
);

CREATE INDEX issue_conversation_workspace_updated
    ON issue_conversation (organization_id, repository, updated_at DESC);
CREATE INDEX issue_conversation_runner_claim
    ON issue_conversation (organization_id, status, created_at);

CREATE TABLE issue_conversation_message (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id varchar(36) NOT NULL REFERENCES issue_conversation(id) ON DELETE CASCADE,
    role varchar(16) NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL
);

CREATE INDEX issue_conversation_message_order
    ON issue_conversation_message (conversation_id, created_at, id);
