CREATE TABLE test_check_evidence (
    id VARCHAR(36) PRIMARY KEY,
    task_id VARCHAR(36) NOT NULL REFERENCES delivery_task(id) ON DELETE CASCADE,
    runner_id VARCHAR(36) NOT NULL REFERENCES runner(id),
    gate_id VARCHAR(36) NOT NULL REFERENCES verification_gate(id),
    lease_id VARCHAR(36) NOT NULL,
    check_kind VARCHAR(8) NOT NULL CHECK (check_kind IN ('RED','GREEN')),
    image VARCHAR(255) NOT NULL,
    command VARCHAR(8000) NOT NULL,
    target_sha VARCHAR(64) NOT NULL,
    parent_sha VARCHAR(64),
    verdict VARCHAR(20) NOT NULL CHECK (verdict IN ('PASS','FAIL','UNVERIFIABLE')),
    reason VARCHAR(48) NOT NULL,
    before_status VARCHAR(16),
    after_status VARCHAR(16) NOT NULL,
    before_exit_code INTEGER,
    after_exit_code INTEGER NOT NULL,
    before_timed_out BOOLEAN NOT NULL DEFAULT FALSE,
    after_timed_out BOOLEAN NOT NULL,
    before_total INTEGER,
    before_passed INTEGER,
    before_failed INTEGER,
    before_errored INTEGER,
    before_skipped INTEGER,
    after_total INTEGER NOT NULL,
    after_passed INTEGER NOT NULL,
    after_failed INTEGER NOT NULL,
    after_errored INTEGER NOT NULL,
    after_skipped INTEGER NOT NULL,
    red_tests VARCHAR(262144),
    failing_tests VARCHAR(4000),
    classified_tests VARCHAR(65536),
    changed_files VARCHAR(65536),
    before_outcome_digest VARCHAR(64),
    after_outcome_digest VARCHAR(64) NOT NULL,
    before_output_digest VARCHAR(64),
    after_output_digest VARCHAR(64) NOT NULL,
    artifact_reference VARCHAR(1000) NOT NULL,
    bundle_digest VARCHAR(64) NOT NULL,
    digest VARCHAR(64) NOT NULL UNIQUE,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX ix_test_check_evidence_task_recorded
    ON test_check_evidence (task_id, recorded_at ASC);
