const endpoint = import.meta.env.VITE_GRAPHQL_URL ?? '/graphql';

export type IssueIntakeCheck = { eligible: boolean; reasons: string[]; checkedAt: string };
export function checkIssueIntake(repository: string, issueNumber: number): Promise<IssueIntakeCheck> {
  return request<{ issueIntakeCheck: IssueIntakeCheck }>('query($repository:String!,$issueNumber:Int!){issueIntakeCheck(repository:$repository,issueNumber:$issueNumber){eligible reasons checkedAt}}', { repository, issueNumber }).then(data => data.issueIntakeCheck);
}

export type Runner = { id:string; name:string; version:string; enabled:boolean; lastHeartbeatAt:string; capabilities:string[] };
export function loadRunners(organizationId:string):Promise<Runner[]> { return request<{runners:Runner[]}>('query($organizationId:String!){runners(organizationId:$organizationId){id name version enabled lastHeartbeatAt capabilities}}',{organizationId}).then(data=>data.runners); }
export function issueRunnerToken(organizationId:string):Promise<string> { return request<{issueRunnerRegistrationToken:string}>('mutation($organizationId:String!){issueRunnerRegistrationToken(organizationId:$organizationId)}',{organizationId}).then(data=>data.issueRunnerRegistrationToken); }
export function archiveRun(runId:string,archived:boolean):Promise<FeatureRun> { return request<{archiveFeatureRun:FeatureRun}>(`mutation($runId:ID!,$archived:Boolean!){archiveFeatureRun(runId:$runId,archived:$archived){${runFields}}}`,{runId,archived}).then(data=>data.archiveFeatureRun); }
export function deleteRun(runId:string):Promise<boolean> { return request<{deleteFeatureRun:boolean}>('mutation($runId:ID!){deleteFeatureRun(runId:$runId)}',{runId}).then(data=>data.deleteFeatureRun); }
export function configureIntake(repository:string,requireAssignee:boolean,requiredAssignee:string):Promise<RepositoryConnection> { return request<{configureRepositoryIntake:RepositoryConnection}>('mutation($repository:String!,$requireAssignee:Boolean!,$requiredAssignee:String){configureRepositoryIntake(repository:$repository,requireAssignee:$requireAssignee,requiredAssignee:$requiredAssignee){id repository requiredAssignee requireAssignee installationId enabled defaultBranch issueLabel harnessProfile requiredGates maxBudgetUsd policyRevision}}',{repository,requireAssignee,requiredAssignee}).then(data=>data.configureRepositoryIntake); }

export type RepositoryIssueProposal = { id:string; repository:string; status:string; createdAt:string; startedAt?:string; completedAt?:string; failureSummary?:string; proposedTitle?:string; proposedBody?:string; acceptanceCriteria:string[]; provider?:string; model?:string; inputTokens:number; outputTokens:number; estimatedCostMicros:number; costKnown:boolean; issueNumber?:number; issueUrl?:string };
export type RepositoryScanFinding = { id:string; severity:string; title:string; description:string; impact:string; evidence:string; affectedFiles:string[]; acceptanceCriteria:string[]; issueNumber?:number; issueUrl?:string; proposal?:RepositoryIssueProposal };
export type RepositoryScan = { id:string; repository:string; baseBranch:string; status:string; requestedBy:string; createdAt:string; startedAt?:string; completedAt?:string; commitSha?:string; provider?:string; model?:string; inputTokens:number; outputTokens:number; estimatedCostMicros:number; costKnown:boolean; failureSummary?:string; findings:RepositoryScanFinding[] };
const proposalFields = 'id repository status createdAt startedAt completedAt failureSummary proposedTitle proposedBody acceptanceCriteria provider model inputTokens outputTokens estimatedCostMicros costKnown issueNumber issueUrl';
const scanFields = `id repository baseBranch status requestedBy createdAt startedAt completedAt commitSha provider model inputTokens outputTokens estimatedCostMicros costKnown failureSummary findings{id severity title description impact evidence affectedFiles acceptanceCriteria issueNumber issueUrl proposal{${proposalFields}}}`;
export function loadRepositoryScans(repository:string):Promise<RepositoryScan[]>{return request<{repositoryScans?:RepositoryScan[]}>(`query($repository:String!){repositoryScans(repository:$repository){${scanFields}}}`,{repository}).then(data=>data.repositoryScans??[]);}
export function requestRepositoryScan(repository:string):Promise<RepositoryScan>{return request<{requestRepositoryScan:RepositoryScan}>(`mutation($repository:String!){requestRepositoryScan(repository:$repository){${scanFields}}}`,{repository}).then(data=>data.requestRepositoryScan);}
export function requestIssueProposal(scanId:string,findingId:string):Promise<RepositoryIssueProposal>{return request<{requestRepositoryIssueProposal:RepositoryIssueProposal}>(`mutation($scanId:ID!,$findingId:ID!){requestRepositoryIssueProposal(scanId:$scanId,findingId:$findingId){${proposalFields}}}`,{scanId,findingId}).then(data=>data.requestRepositoryIssueProposal);}
export function approveIssueProposal(proposalId:string,title:string,body:string,acceptanceCriteria:string[]):Promise<RepositoryIssueProposal>{return request<{approveRepositoryIssueProposal:RepositoryIssueProposal}>(`mutation($proposalId:ID!,$title:String!,$body:String!,$acceptanceCriteria:[String!]!){approveRepositoryIssueProposal(proposalId:$proposalId,title:$title,body:$body,acceptanceCriteria:$acceptanceCriteria){${proposalFields}}}`,{proposalId,title,body,acceptanceCriteria}).then(data=>data.approveRepositoryIssueProposal);}
export function rejectIssueProposal(proposalId:string,reason=''):Promise<RepositoryIssueProposal>{return request<{rejectRepositoryIssueProposal:RepositoryIssueProposal}>(`mutation($proposalId:ID!,$reason:String){rejectRepositoryIssueProposal(proposalId:$proposalId,reason:$reason){${proposalFields}}}`,{proposalId,reason}).then(data=>data.rejectRepositoryIssueProposal);}

export type ProviderAttempt = { id: string; provider: string; model: string; inputTokens: number; outputTokens: number; attemptCount: number; estimatedCostMicros: number; costKnown: boolean; outcome: string; retryable: boolean; category: string; recordedAt: string };
export type ProviderActivity = { id: string; repository: string; activityType: 'REPOSITORY_SCAN' | 'ISSUE_SPECIFICATION' | 'AI_CHAT' | string; provider: string; model: string; inputTokens: number; outputTokens: number; estimatedCostMicros: number; costKnown: boolean; recordedAt: string };
export type IssueChatMessage = { role: 'USER' | 'ASSISTANT'; content: string; createdAt: string };
export type IssueConversation = { id: string; repository: string; status: string; createdAt: string; updatedAt: string; failureSummary?: string; draftTitle?: string; draftBody?: string; acceptanceCriteria: string[]; provider?: string; model?: string; inputTokens: number; outputTokens: number; estimatedCostMicros: number; costKnown: boolean; issueNumber?: number; issueUrl?: string; messages: IssueChatMessage[] };
const issueConversationFields = 'id repository status createdAt updatedAt failureSummary draftTitle draftBody acceptanceCriteria provider model inputTokens outputTokens estimatedCostMicros costKnown issueNumber issueUrl messages{role content createdAt}';
export function loadIssueConversations(repository: string): Promise<IssueConversation[]> { return request<{ issueConversations?: IssueConversation[] }>(`query($repository:String!){issueConversations(repository:$repository){${issueConversationFields}}}`, { repository }).then(data => data.issueConversations ?? []); }
export function loadIssueConversation(id: string): Promise<IssueConversation> { return request<{ issueConversation: IssueConversation }>(`query($id:ID!){issueConversation(id:$id){${issueConversationFields}}}`, { id }).then(data => data.issueConversation); }
export function startIssueConversation(repository: string, message: string): Promise<IssueConversation> { return request<{ startIssueConversation: IssueConversation }>(`mutation($repository:String!,$message:String!){startIssueConversation(repository:$repository,message:$message){${issueConversationFields}}}`, { repository, message }).then(data => data.startIssueConversation); }
export function sendIssueConversationMessage(conversationId: string, message: string): Promise<IssueConversation> { return request<{ sendIssueConversationMessage: IssueConversation }>(`mutation($conversationId:ID!,$message:String!){sendIssueConversationMessage(conversationId:$conversationId,message:$message){${issueConversationFields}}}`, { conversationId, message }).then(data => data.sendIssueConversationMessage); }
export function createIssueFromConversation(conversationId: string, title: string, body: string, acceptanceCriteria: string[]): Promise<IssueConversation> { return request<{ createIssueFromConversation: IssueConversation }>(`mutation($conversationId:ID!,$title:String!,$body:String!,$acceptanceCriteria:[String!]!){createIssueFromConversation(conversationId:$conversationId,title:$title,body:$body,acceptanceCriteria:$acceptanceCriteria){${issueConversationFields}}}`, { conversationId, title, body, acceptanceCriteria }).then(data => data.createIssueFromConversation); }
export type RepairPackage = { id: string; attempt: number; failureCategory: string; changeSha?: string; evidenceDigest?: string; createdAt: string };
export type Task = { id: string; planKey: string; role: string; executionRole: string; title: string; state: string; requiredCapability?: string; attemptBudget: number; attempts: number; budgetMicros: number; spentCostMicros: number; changeSha?: string; ownedPaths: string[]; dependencyKeys: string[]; providerAttempts: ProviderAttempt[]; repairPackages: RepairPackage[] };
export type Gate = { id: string; name: string; required: boolean; state: string; kind?: string; imageDigest?: string; command: string[]; networkPolicy?: string; timeoutSeconds?: number; criterionCoverage?: string };
export type Criterion = { id: string; statement: string; coverageState: string };
export type FeatureRun = { archived: boolean; id: string; repository: string; sourceRef: string; title: string; specification: string; budgetUsd: number; spentCostMicros: number; harnessProfile: string; baseBranch: string; policyRevision: number; state: string; createdAt: string; approved: boolean; approvedAt?: string; approvedBy?: string; publication?: Pick<GithubPublication, 'pullRequestState'> | null; tasks: Task[]; gates: Gate[]; criteria: Criterion[] };
export type VerificationEvidence = { id: string; taskId: string; runnerId: string; kind: string; gate: string; image: string; command: string[]; exitCode: number; timedOut: boolean; output: string; digest: string; startedAt: string; finishedAt: string; artifactReference?: string; recordedAt: string };
export type ReviewCriterionAssessment = { id: string; statement: string; status: 'PASS' | 'FAIL'; evidence: string };
export type ReviewEvidence = { id: string; taskId: string; runnerId: string; approved: boolean; summary: string; digest: string; recordedAt: string; criteria: ReviewCriterionAssessment[] };
export type ArtifactMetadata = { id: string; taskId: string; leaseId: string; storageReference: string; contentType: string; artifactType: string; displayName: string; sizeBytes: number; sha256: string; retentionClass: string; retainUntil: string; createdAt: string };
export type AuditEvent = { id: string; actor: string; action: string; resourceType: string; resourceId: string; payloadDigest: string; occurredAt: string };
export type GithubPublication = { repository: string; branch: string; headSha?: string; pullRequestNumber?: number; pullRequestState: string; deliveredAt?: string; autoMergeRequested:boolean; mergedAt?:string; mergeSha?:string };
export type RunnerEvent = { id: string; taskId: string; runnerId: string; sequenceNumber: number; level: string; eventType: string; message: string; occurredAt: string };
export type HumanEscalation = { id: string; taskId?: string; reason: string; severity: string; status: string; summary: string; createdAt: string; acknowledgedAt?: string; acknowledgedBy?: string };
export type OperatorSession = { subject: string; organizationId: string; role: 'ADMIN' | 'OPERATOR' | 'VIEWER' };
export type OrganizationMember = { id: string; organizationId: string; organizationName: string; subject: string; githubLogin?: string; role: OperatorSession['role']; accepted: boolean };
const memberFields = 'id organizationId organizationName subject githubLogin role accepted';
export function loadMyOrganizations(): Promise<OrganizationMember[]> {
  return request<{myOrganizationMemberships?:OrganizationMember[]}>(`query{myOrganizationMemberships{${memberFields}}}`).then(data => data.myOrganizationMemberships ?? []);
}
export function selectOrganization(organizationId: string): Promise<OperatorSession> {
  return request<{selectOrganization:OperatorSession}>('mutation($organizationId:String!){selectOrganization(organizationId:$organizationId){subject organizationId role}}',{organizationId}).then(data => data.selectOrganization);
}
export function loadOrganizationMembers(organizationId: string): Promise<OrganizationMember[]> {
  return request<{organizationMemberships: OrganizationMember[]}>(`query($organizationId:String!){organizationMemberships(organizationId:$organizationId){${memberFields}}}`, {organizationId}).then(data => data.organizationMemberships);
}
export function inviteGithubUser(organizationId: string, login: string, role: OperatorSession['role']): Promise<OrganizationMember> {
  return request<{inviteGithubUser: OrganizationMember}>(`mutation($organizationId:String!,$login:String!,$role:OperatorRole!){inviteGithubUser(organizationId:$organizationId,login:$login,role:$role){${memberFields}}}`, {organizationId,login,role}).then(data => data.inviteGithubUser);
}
export function revokeOrganizationMember(organizationId: string, membershipId: string): Promise<boolean> {
  return request<{revokeOrganizationMembership:boolean}>('mutation($organizationId:String!,$membershipId:ID!){revokeOrganizationMembership(organizationId:$organizationId,membershipId:$membershipId)}', {organizationId,membershipId}).then(data => data.revokeOrganizationMembership);
}
export type SubmitFeature = { repository: string; sourceRef: string; title: string; specification: string; budgetUsd: number };
export type RepositoryConnection = { requiredAssignee?: string; requireAssignee:boolean; id: string; repository: string; installationId: number; enabled: boolean; defaultBranch: string; issueLabel: string; harnessProfile: string; requiredGates: string[]; maxBudgetUsd: number; policyRevision: number };
export type ConnectRepository = Omit<RepositoryConnection, 'id' | 'enabled' | 'policyRevision' | 'requireAssignee'>;
export type RunComparison = { dimension:string; name:string; runCount:number; requestCount:number; successfulRequests:number; inputTokens:number; outputTokens:number; knownCostMicros:number };
export type RunAnalytics = { totalRuns:number; activeRuns:number; deliveredRuns:number; providerRequests:number; inputTokens:number; outputTokens:number; knownCostMicros:number; costCoverage:number; modelComparisons:RunComparison[]; harnessComparisons:RunComparison[] };
export type RunOperations = { evidence: VerificationEvidence[]; reviews: ReviewEvidence[]; artifacts: ArtifactMetadata[]; events: RunnerEvent[]; escalations: HumanEscalation[]; audit: AuditEvent[]; publication?: GithubPublication };
export type OrganizationPolicy = { organizationId:string; maxRunBudgetUsd:number; maxParallelTasks:number; allowedProviders:string[]; requireHumanApproval:boolean; autoMergeEnabled:boolean; revision:number };
export type HarnessDefinition = { id:string; organizationId:string; name:string; description:string; allowedRoles:string[]; defaultAttemptBudget:number; enabled:boolean; revision:number };
export type LocalMcpConfiguration = { id:string; name:string; command:string; arguments:string[]; allowedRoles:string[]; contextTool:string; toolArguments:string; enabled:boolean; revision:number };
export type PlatformConfiguration = { policy:OrganizationPolicy; harnesses:HarnessDefinition[]; mcp:LocalMcpConfiguration[] };

const taskFields = `id planKey role executionRole title state requiredCapability attemptBudget attempts budgetMicros spentCostMicros changeSha ownedPaths dependencyKeys providerAttempts { id provider model inputTokens outputTokens attemptCount estimatedCostMicros costKnown outcome retryable category recordedAt } repairPackages { id attempt failureCategory changeSha evidenceDigest createdAt }`;
const runFields = `archived id repository sourceRef title specification budgetUsd spentCostMicros harnessProfile baseBranch policyRevision state createdAt approved approvedAt approvedBy publication { pullRequestState } tasks { ${taskFields} } gates { id name required state kind imageDigest command networkPolicy timeoutSeconds criterionCoverage } criteria { id statement coverageState }`;

export function approveRunnerPairing(challenge:string,name:string):Promise<boolean>{return request<{approveRunnerPairing:boolean}>('mutation($challenge:String!,$name:String!){approveRunnerPairing(challenge:$challenge,name:$name)}',{challenge,name}).then(data=>data.approveRunnerPairing);}
async function request<T>(query: string, variables: Record<string, unknown> = {}): Promise<T> {
  const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables }) });
  const body = await response.json() as { data?: T; errors?: Array<{ message?: string }> };
  if (!response.ok || body.errors?.length || !body.data) throw new Error(body.errors?.[0]?.message ?? 'ForgeLoop control plane request failed');
  return body.data;
}

export function loadRuns(): Promise<FeatureRun[]> { return request<{ featureRuns?: FeatureRun[] }>(`query { featureRuns { ${runFields} } }`).then(data => data.featureRuns ?? []); }
export function loadProviderActivities(days:number,repository:string):Promise<ProviderActivity[]>{return request<{providerActivities?:ProviderActivity[]}>('query($days:Int!,$repository:String){providerActivities(days:$days,repository:$repository){id repository activityType provider model inputTokens outputTokens estimatedCostMicros costKnown recordedAt}}',{days,repository:repository||null}).then(data=>data.providerActivities??[]);}
export function loadRunAnalytics():Promise<RunAnalytics>{return request<{runAnalytics:RunAnalytics}>('query { runAnalytics { totalRuns activeRuns deliveredRuns providerRequests inputTokens outputTokens knownCostMicros costCoverage modelComparisons { dimension name runCount requestCount successfulRequests inputTokens outputTokens knownCostMicros } harnessComparisons { dimension name runCount requestCount successfulRequests inputTokens outputTokens knownCostMicros } } }').then(data=>data.runAnalytics);}
export function loadRun(id: string): Promise<FeatureRun> { return request<{ featureRun: FeatureRun }>(`query($id: ID!) { featureRun(id: $id) { ${runFields} } }`, { id }).then(data => data.featureRun); }
export function loadOperator(): Promise<OperatorSession> { return request<{ currentOperator: OperatorSession }>('query { currentOperator { subject organizationId role } }').then(data => data.currentOperator); }
export function loadRunOperations(runId: string): Promise<RunOperations> { return request<{ featureRunEvidence?: VerificationEvidence[]; featureRunReviewEvidence?: ReviewEvidence[]; featureRunArtifacts?: ArtifactMetadata[]; featureRunEvents?: RunnerEvent[]; featureRunEscalations?: HumanEscalation[]; featureRunAuditEvents?: AuditEvent[]; featureRunPublication?: GithubPublication }>('query($runId: ID!) { featureRunEvidence(runId: $runId) { id taskId runnerId kind gate image command exitCode timedOut output digest startedAt finishedAt artifactReference recordedAt } featureRunReviewEvidence(runId: $runId) { id taskId runnerId approved summary digest recordedAt criteria { id statement status evidence } } featureRunArtifacts(runId: $runId) { id taskId leaseId storageReference contentType artifactType displayName sizeBytes sha256 retentionClass retainUntil createdAt } featureRunEvents(runId: $runId) { id taskId runnerId sequenceNumber level eventType message occurredAt } featureRunEscalations(runId: $runId) { id taskId reason severity status summary createdAt acknowledgedAt acknowledgedBy } featureRunAuditEvents(runId: $runId) { id actor action resourceType resourceId payloadDigest occurredAt } featureRunPublication(runId: $runId) { repository branch headSha pullRequestNumber pullRequestState deliveredAt autoMergeRequested mergedAt mergeSha } }', { runId }).then(data => ({ evidence: data.featureRunEvidence ?? [], reviews: data.featureRunReviewEvidence ?? [], artifacts: data.featureRunArtifacts ?? [], events: data.featureRunEvents ?? [], escalations: data.featureRunEscalations ?? [], audit: data.featureRunAuditEvents ?? [], publication: data.featureRunPublication })); }
export function submitFeature(input: SubmitFeature): Promise<FeatureRun> { return request<{ submitFeature: FeatureRun }>(`mutation($input: SubmitFeatureInput!) { submitFeature(input: $input) { ${runFields} } }`, { input }).then(data => data.submitFeature); }
export function cancelFeatureRun(runId: string): Promise<FeatureRun> { return request<{ cancelFeatureRun: FeatureRun }>(`mutation($runId: ID!) { cancelFeatureRun(runId: $runId, confirmation: "CANCEL") { ${runFields} } }`, { runId }).then(data => data.cancelFeatureRun); }
export function approveFeatureRun(runId: string): Promise<FeatureRun> { return request<{ approveFeatureRun: FeatureRun }>(`mutation($runId: ID!) { approveFeatureRun(runId: $runId, confirmation: "APPROVE") { ${runFields} } }`, { runId }).then(data => data.approveFeatureRun); }
export function retryFeatureTask(taskId: string, reason: string): Promise<Task> { return request<{ retryFeatureTask: Task }>(`mutation($taskId: ID!, $reason: String!) { retryFeatureTask(taskId: $taskId, reason: $reason, confirmation: "RETRY") { ${taskFields} } }`, { taskId, reason }).then(data => data.retryFeatureTask); }
export function acknowledgeEscalation(id:string):Promise<HumanEscalation>{return request<{acknowledgeEscalation:HumanEscalation}>('mutation($id:ID!){acknowledgeEscalation(id:$id,confirmation:"ACKNOWLEDGE"){id status acknowledgedAt acknowledgedBy reason severity summary createdAt}}',{id}).then(data=>data.acknowledgeEscalation);}
export function resolveEscalation(id:string):Promise<HumanEscalation>{return request<{resolveEscalation:HumanEscalation}>('mutation($id:ID!){resolveEscalation(id:$id,confirmation:"RESOLVE"){id status resolvedAt resolvedBy reason severity summary createdAt}}',{id}).then(data=>data.resolveEscalation);}
export function loadRepositoryConnections(): Promise<RepositoryConnection[]> { return request<{ repositoryConnections?: RepositoryConnection[] }>('query { repositoryConnections { id repository requiredAssignee requireAssignee installationId enabled defaultBranch issueLabel harnessProfile requiredGates maxBudgetUsd policyRevision } }').then(data => data.repositoryConnections ?? []); }
export function connectRepository(input: ConnectRepository): Promise<RepositoryConnection> { return request<{ connectRepository: RepositoryConnection }>('mutation($input: ConnectRepositoryInput!) { connectRepository(input: $input) { id repository requiredAssignee requireAssignee installationId enabled defaultBranch issueLabel harnessProfile requiredGates maxBudgetUsd policyRevision } }', { input }).then(data => data.connectRepository); }
export function loadPlatformConfiguration():Promise<PlatformConfiguration>{return request<{organizationPolicy:OrganizationPolicy;harnessDefinitions:HarnessDefinition[];localMcpConfigurations:LocalMcpConfiguration[]}>('query { organizationPolicy { organizationId maxRunBudgetUsd maxParallelTasks allowedProviders requireHumanApproval autoMergeEnabled revision } harnessDefinitions { id organizationId name description allowedRoles defaultAttemptBudget enabled revision } localMcpConfigurations { id name command arguments allowedRoles contextTool toolArguments enabled revision } }').then(data=>({policy:data.organizationPolicy,harnesses:data.harnessDefinitions,mcp:data.localMcpConfigurations}));}
export function configureOrganizationPolicy(input:Omit<OrganizationPolicy,'organizationId'|'revision'>):Promise<OrganizationPolicy>{return request<{configureOrganizationPolicy:OrganizationPolicy}>('mutation($input:OrganizationPolicyInput!){configureOrganizationPolicy(input:$input){organizationId maxRunBudgetUsd maxParallelTasks allowedProviders requireHumanApproval autoMergeEnabled revision}}',{input}).then(data=>data.configureOrganizationPolicy);}
export function createHarnessDefinition(input:{name:string;description:string;allowedRoles:string[];defaultAttemptBudget:number}):Promise<HarnessDefinition>{return request<{createHarnessDefinition:HarnessDefinition}>('mutation($input:HarnessDefinitionInput!){createHarnessDefinition(input:$input){id organizationId name description allowedRoles defaultAttemptBudget enabled revision}}',{input}).then(data=>data.createHarnessDefinition);}
export function createLocalMcpConfiguration(input:{name:string;command:string;arguments:string[];allowedRoles:string[];contextTool:string;toolArguments:string}):Promise<LocalMcpConfiguration>{return request<{createLocalMcpConfiguration:LocalMcpConfiguration}>('mutation($input:LocalMcpConfigurationInput!){createLocalMcpConfiguration(input:$input){id name command arguments allowedRoles contextTool toolArguments enabled revision}}',{input}).then(data=>data.createLocalMcpConfiguration);}
