const endpoint = import.meta.env.VITE_GRAPHQL_URL ?? '/graphql';

export type ProviderAttempt = { id: string; provider: string; model: string; inputTokens: number; outputTokens: number; attemptCount: number; estimatedCostMicros: number; costKnown: boolean; outcome: string; retryable: boolean; category: string; recordedAt: string };
export type RepairPackage = { id: string; attempt: number; failureCategory: string; changeSha?: string; evidenceDigest?: string; createdAt: string };
export type Task = { id: string; planKey: string; role: string; executionRole: string; title: string; state: string; attemptBudget: number; attempts: number; budgetMicros: number; spentCostMicros: number; changeSha?: string; ownedPaths: string[]; dependencyKeys: string[]; providerAttempts: ProviderAttempt[]; repairPackages: RepairPackage[] };
export type Gate = { id: string; name: string; required: boolean; state: string; kind?: string; imageDigest?: string; command: string[]; networkPolicy?: string; timeoutSeconds?: number; criterionCoverage?: string };
export type Criterion = { id: string; statement: string; coverageState: string };
export type FeatureRun = { id: string; repository: string; sourceRef: string; title: string; specification: string; budgetUsd: number; spentCostMicros: number; harnessProfile: string; baseBranch: string; policyRevision: number; state: string; createdAt: string; approved: boolean; approvedAt?: string; approvedBy?: string; tasks: Task[]; gates: Gate[]; criteria: Criterion[] };
export type VerificationEvidence = { id: string; taskId: string; runnerId: string; kind: string; gate: string; image: string; command: string[]; exitCode: number; timedOut: boolean; output: string; digest: string; startedAt: string; finishedAt: string; artifactReference?: string; recordedAt: string };
export type ReviewCriterionAssessment = { id: string; statement: string; status: 'PASS' | 'FAIL'; evidence: string };
export type ReviewEvidence = { id: string; taskId: string; runnerId: string; approved: boolean; summary: string; digest: string; recordedAt: string; criteria: ReviewCriterionAssessment[] };
export type ArtifactMetadata = { id: string; taskId: string; leaseId: string; storageReference: string; contentType: string; artifactType: string; displayName: string; sizeBytes: number; sha256: string; retentionClass: string; retainUntil: string; createdAt: string };
export type AuditEvent = { id: string; actor: string; action: string; resourceType: string; resourceId: string; payloadDigest: string; occurredAt: string };
export type GithubPublication = { repository: string; branch: string; headSha?: string; pullRequestNumber?: number; deliveredAt?: string };
export type RunnerEvent = { id: string; taskId: string; runnerId: string; sequenceNumber: number; level: string; eventType: string; message: string; occurredAt: string };
export type HumanEscalation = { id: string; taskId?: string; reason: string; severity: string; status: string; summary: string; createdAt: string; acknowledgedAt?: string; acknowledgedBy?: string };
export type OperatorSession = { subject: string; organizationId: string; role: 'ADMIN' | 'OPERATOR' | 'VIEWER' };
export type SubmitFeature = { repository: string; sourceRef: string; title: string; specification: string; budgetUsd: number };
export type RepositoryConnection = { id: string; repository: string; installationId: number; enabled: boolean; defaultBranch: string; issueLabel: string; harnessProfile: string; requiredGates: string[]; maxBudgetUsd: number; policyRevision: number };
export type ConnectRepository = Omit<RepositoryConnection, 'id' | 'enabled' | 'policyRevision'>;
export type RunComparison = { dimension:string; name:string; runCount:number; requestCount:number; successfulRequests:number; inputTokens:number; outputTokens:number; knownCostMicros:number };
export type RunAnalytics = { totalRuns:number; activeRuns:number; deliveredRuns:number; providerRequests:number; inputTokens:number; outputTokens:number; knownCostMicros:number; costCoverage:number; modelComparisons:RunComparison[]; harnessComparisons:RunComparison[] };
export type RunOperations = { evidence: VerificationEvidence[]; reviews: ReviewEvidence[]; artifacts: ArtifactMetadata[]; events: RunnerEvent[]; escalations: HumanEscalation[]; audit: AuditEvent[]; publication?: GithubPublication };
export type OrganizationPolicy = { organizationId:string; maxRunBudgetUsd:number; maxParallelTasks:number; allowedProviders:string[]; requireHumanApproval:boolean; revision:number };
export type HarnessDefinition = { id:string; organizationId:string; name:string; description:string; allowedRoles:string[]; defaultAttemptBudget:number; enabled:boolean; revision:number };
export type LocalMcpConfiguration = { id:string; name:string; command:string; arguments:string[]; allowedRoles:string[]; contextTool:string; toolArguments:string; enabled:boolean; revision:number };
export type PlatformConfiguration = { policy:OrganizationPolicy; harnesses:HarnessDefinition[]; mcp:LocalMcpConfiguration[] };

const taskFields = `id planKey role executionRole title state attemptBudget attempts budgetMicros spentCostMicros changeSha ownedPaths dependencyKeys providerAttempts { id provider model inputTokens outputTokens attemptCount estimatedCostMicros costKnown outcome retryable category recordedAt } repairPackages { id attempt failureCategory changeSha evidenceDigest createdAt }`;
const runFields = `id repository sourceRef title specification budgetUsd spentCostMicros harnessProfile baseBranch policyRevision state createdAt approved approvedAt approvedBy tasks { ${taskFields} } gates { id name required state kind imageDigest command networkPolicy timeoutSeconds criterionCoverage } criteria { id statement coverageState }`;

async function request<T>(query: string, variables: Record<string, unknown> = {}): Promise<T> {
  const response = await fetch(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ query, variables }) });
  const body = await response.json() as { data?: T; errors?: Array<{ message?: string }> };
  if (!response.ok || body.errors?.length || !body.data) throw new Error(body.errors?.[0]?.message ?? 'ForgeLoop control plane request failed');
  return body.data;
}

export function loadRuns(): Promise<FeatureRun[]> { return request<{ featureRuns?: FeatureRun[] }>(`query { featureRuns { ${runFields} } }`).then(data => data.featureRuns ?? []); }
export function loadRunAnalytics():Promise<RunAnalytics>{return request<{runAnalytics:RunAnalytics}>('query { runAnalytics { totalRuns activeRuns deliveredRuns providerRequests inputTokens outputTokens knownCostMicros costCoverage modelComparisons { dimension name runCount requestCount successfulRequests inputTokens outputTokens knownCostMicros } harnessComparisons { dimension name runCount requestCount successfulRequests inputTokens outputTokens knownCostMicros } } }').then(data=>data.runAnalytics);}
export function loadRun(id: string): Promise<FeatureRun> { return request<{ featureRun: FeatureRun }>(`query($id: ID!) { featureRun(id: $id) { ${runFields} } }`, { id }).then(data => data.featureRun); }
export function loadOperator(): Promise<OperatorSession> { return request<{ currentOperator: OperatorSession }>('query { currentOperator { subject organizationId role } }').then(data => data.currentOperator); }
export function loadRunOperations(runId: string): Promise<RunOperations> { return request<{ featureRunEvidence?: VerificationEvidence[]; featureRunReviewEvidence?: ReviewEvidence[]; featureRunArtifacts?: ArtifactMetadata[]; featureRunEvents?: RunnerEvent[]; featureRunEscalations?: HumanEscalation[]; featureRunAuditEvents?: AuditEvent[]; featureRunPublication?: GithubPublication }>('query($runId: ID!) { featureRunEvidence(runId: $runId) { id taskId runnerId kind gate image command exitCode timedOut output digest startedAt finishedAt artifactReference recordedAt } featureRunReviewEvidence(runId: $runId) { id taskId runnerId approved summary digest recordedAt criteria { id statement status evidence } } featureRunArtifacts(runId: $runId) { id taskId leaseId storageReference contentType artifactType displayName sizeBytes sha256 retentionClass retainUntil createdAt } featureRunEvents(runId: $runId) { id taskId runnerId sequenceNumber level eventType message occurredAt } featureRunEscalations(runId: $runId) { id taskId reason severity status summary createdAt acknowledgedAt acknowledgedBy } featureRunAuditEvents(runId: $runId) { id actor action resourceType resourceId payloadDigest occurredAt } featureRunPublication(runId: $runId) { repository branch headSha pullRequestNumber deliveredAt } }', { runId }).then(data => ({ evidence: data.featureRunEvidence ?? [], reviews: data.featureRunReviewEvidence ?? [], artifacts: data.featureRunArtifacts ?? [], events: data.featureRunEvents ?? [], escalations: data.featureRunEscalations ?? [], audit: data.featureRunAuditEvents ?? [], publication: data.featureRunPublication })); }
export function submitFeature(input: SubmitFeature): Promise<FeatureRun> { return request<{ submitFeature: FeatureRun }>(`mutation($input: SubmitFeatureInput!) { submitFeature(input: $input) { ${runFields} } }`, { input }).then(data => data.submitFeature); }
export function cancelFeatureRun(runId: string): Promise<FeatureRun> { return request<{ cancelFeatureRun: FeatureRun }>(`mutation($runId: ID!) { cancelFeatureRun(runId: $runId, confirmation: "CANCEL") { ${runFields} } }`, { runId }).then(data => data.cancelFeatureRun); }
export function approveFeatureRun(runId: string): Promise<FeatureRun> { return request<{ approveFeatureRun: FeatureRun }>(`mutation($runId: ID!) { approveFeatureRun(runId: $runId, confirmation: "APPROVE") { ${runFields} } }`, { runId }).then(data => data.approveFeatureRun); }
export function retryFeatureTask(taskId: string, reason: string): Promise<Task> { return request<{ retryFeatureTask: Task }>(`mutation($taskId: ID!, $reason: String!) { retryFeatureTask(taskId: $taskId, reason: $reason, confirmation: "RETRY") { ${taskFields} } }`, { taskId, reason }).then(data => data.retryFeatureTask); }
export function acknowledgeEscalation(id:string):Promise<HumanEscalation>{return request<{acknowledgeEscalation:HumanEscalation}>('mutation($id:ID!){acknowledgeEscalation(id:$id,confirmation:"ACKNOWLEDGE"){id status acknowledgedAt acknowledgedBy reason severity summary createdAt}}',{id}).then(data=>data.acknowledgeEscalation);}
export function resolveEscalation(id:string):Promise<HumanEscalation>{return request<{resolveEscalation:HumanEscalation}>('mutation($id:ID!){resolveEscalation(id:$id,confirmation:"RESOLVE"){id status resolvedAt resolvedBy reason severity summary createdAt}}',{id}).then(data=>data.resolveEscalation);}
export function loadRepositoryConnections(): Promise<RepositoryConnection[]> { return request<{ repositoryConnections?: RepositoryConnection[] }>('query { repositoryConnections { id repository installationId enabled defaultBranch issueLabel harnessProfile requiredGates maxBudgetUsd policyRevision } }').then(data => data.repositoryConnections ?? []); }
export function connectRepository(input: ConnectRepository): Promise<RepositoryConnection> { return request<{ connectRepository: RepositoryConnection }>('mutation($input: ConnectRepositoryInput!) { connectRepository(input: $input) { id repository installationId enabled defaultBranch issueLabel harnessProfile requiredGates maxBudgetUsd policyRevision } }', { input }).then(data => data.connectRepository); }
export function loadPlatformConfiguration():Promise<PlatformConfiguration>{return request<{organizationPolicy:OrganizationPolicy;harnessDefinitions:HarnessDefinition[];localMcpConfigurations:LocalMcpConfiguration[]}>('query { organizationPolicy { organizationId maxRunBudgetUsd maxParallelTasks allowedProviders requireHumanApproval revision } harnessDefinitions { id organizationId name description allowedRoles defaultAttemptBudget enabled revision } localMcpConfigurations { id name command arguments allowedRoles contextTool toolArguments enabled revision } }').then(data=>({policy:data.organizationPolicy,harnesses:data.harnessDefinitions,mcp:data.localMcpConfigurations}));}
export function configureOrganizationPolicy(input:Omit<OrganizationPolicy,'organizationId'|'revision'>):Promise<OrganizationPolicy>{return request<{configureOrganizationPolicy:OrganizationPolicy}>('mutation($input:OrganizationPolicyInput!){configureOrganizationPolicy(input:$input){organizationId maxRunBudgetUsd maxParallelTasks allowedProviders requireHumanApproval revision}}',{input}).then(data=>data.configureOrganizationPolicy);}
export function createHarnessDefinition(input:{name:string;description:string;allowedRoles:string[];defaultAttemptBudget:number}):Promise<HarnessDefinition>{return request<{createHarnessDefinition:HarnessDefinition}>('mutation($input:HarnessDefinitionInput!){createHarnessDefinition(input:$input){id organizationId name description allowedRoles defaultAttemptBudget enabled revision}}',{input}).then(data=>data.createHarnessDefinition);}
export function createLocalMcpConfiguration(input:{name:string;command:string;arguments:string[];allowedRoles:string[];contextTool:string;toolArguments:string}):Promise<LocalMcpConfiguration>{return request<{createLocalMcpConfiguration:LocalMcpConfiguration}>('mutation($input:LocalMcpConfigurationInput!){createLocalMcpConfiguration(input:$input){id name command arguments allowedRoles contextTool toolArguments enabled revision}}',{input}).then(data=>data.createLocalMcpConfiguration);}
