import { FormEvent, useEffect, useMemo, useState } from 'react';
import { loadRuns, submitFeature, type FeatureRun, type SubmitFeature } from './api';
import './styles.css';

const blankSubmission: SubmitFeature = { repository: '', sourceRef: '', title: '', specification: '', budgetUsd: 25 };
const pages = ['Runs', 'Repositories', 'Runners', 'MCP', 'Models', 'Evidence'] as const;
export function readable(value: string) { return value.replaceAll('_', ' ').toLowerCase().replace(/\b\w/g, letter => letter.toUpperCase()); }

function SubmissionForm({ onCreated }: { onCreated: (run: FeatureRun) => void }) {
  const [input, setInput] = useState(blankSubmission); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); try { onCreated(await submitFeature(input)); setInput(blankSubmission); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create run'); } finally { setSaving(false); } }
  return <form className="submission" onSubmit={event => void submit(event)}><h2>Start a delivery run</h2><p>Submit an authorized GitHub repository and issue or specification. Repository policy determines execution and verification.</p><div className="form-grid"><label>Repository<input aria-label="Repository" value={input.repository} required placeholder="owner/repository" onChange={event => setInput({ ...input, repository: event.target.value })} /></label><label>Issue or source reference<input aria-label="Issue or source reference" value={input.sourceRef} required placeholder="issue-142" onChange={event => setInput({ ...input, sourceRef: event.target.value })} /></label></div><label>Title<input aria-label="Title" value={input.title} required placeholder="Implement a bounded feature" onChange={event => setInput({ ...input, title: event.target.value })} /></label><label>Specification<textarea aria-label="Specification" value={input.specification} required placeholder={'- First acceptance criterion\n- Second acceptance criterion'} onChange={event => setInput({ ...input, specification: event.target.value })} /></label><label>Budget in USD<input aria-label="Budget in USD" type="number" min="0.01" max="500" step="0.01" value={input.budgetUsd} required onChange={event => setInput({ ...input, budgetUsd: Number(event.target.value) })} /></label><button className="primary" disabled={saving}>{saving ? 'Creating run…' : 'Create delivery run'}</button>{error && <p role="alert">{error}</p>}</form>;
}

function RunDetail({ run }: { run: FeatureRun }) {
  const passingGates = run.gates.filter(gate => gate.state === 'PASSED').length;
  return <section className="detail" aria-labelledby="run-title"><div className="section-heading"><div><p className="eyebrow">{run.repository} · {run.sourceRef}</p><h2 id="run-title">{run.title}</h2></div><span className={`status ${run.state.toLowerCase()}`}>{readable(run.state)}</span></div><div className="summary"><article><b>{run.tasks.length}</b><span>Tasks</span></article><article><b>{passingGates}/{run.gates.length}</b><span>Required gates passed</span></article><article><b>${run.budgetUsd.toFixed(2)}</b><span>Run budget</span></article><article><b>{run.criteria.length}</b><span>Acceptance criteria</span></article></div><div className="detail-grid"><section><h3>Task graph</h3>{run.tasks.map(task => <div className="item" key={task.id}><div><b>{readable(task.role)}</b><small>{task.title}</small></div><span>{readable(task.state)} · {task.attempts}/{task.attemptBudget} attempts</span></div>)}</section><section><h3>Verification gates</h3>{run.gates.map(gate => <div className="item" key={gate.id}><div><b>{readable(gate.name)}</b><small>{gate.required ? 'Required by repository policy' : 'Optional'}</small></div><span>{readable(gate.state)}</span></div>)}</section></div></section>;
}

function App() {
  const [activePage, setActivePage] = useState<(typeof pages)[number]>('Runs'); const [runs, setRuns] = useState<FeatureRun[]>([]); const [selectedId, setSelectedId] = useState<string>(); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { void loadRuns().then(result => { setRuns(result); setSelectedId(result[0]?.id); }).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load delivery runs')).finally(() => setLoading(false)); }, []);
  const selected = useMemo(() => runs.find(run => run.id === selectedId) ?? runs[0], [runs, selectedId]); function created(run: FeatureRun) { setRuns(current => [run, ...current]); setSelectedId(run.id); setActivePage('Runs'); }
  return <main><header><div><a className="brand" href="/">ForgeLoop</a><span>Autonomous software delivery control plane</span></div><div className="connection"><i /> Control plane connected</div></header><div className="shell"><aside><nav aria-label="ForgeLoop navigation">{pages.map(page => <button key={page} className={activePage === page ? 'active' : ''} onClick={() => setActivePage(page)}>{page}</button>)}</nav><p className="sidebar-note">Ticketly and every other target application are external repositories. ForgeLoop stores orchestration state and evidence—not application tickets.</p></aside><div className="content">{activePage === 'Runs' ? <><section className="hero"><p className="eyebrow">Delivery operations</p><h1>Verified changes, not agent claims.</h1><p>Each delivery run is bounded by repository policy, isolated execution, and objective verification evidence.</p></section><SubmissionForm onCreated={created} /><section className="runs"><div className="section-heading"><h2>Delivery runs</h2><span>{runs.length} recorded</span></div>{loading && <p className="loading">Loading control-plane state…</p>}{error && <p role="alert">{error}</p>}{!loading && !error && runs.length === 0 && <p className="empty">No delivery runs yet. Connect a repository through the GitHub App, then create a run from an allowed issue or specification.</p>}{runs.map(run => <button className={`run ${selected?.id === run.id ? 'selected' : ''}`} key={run.id} onClick={() => setSelectedId(run.id)}><span className={`status ${run.state.toLowerCase()}`}>{readable(run.state)}</span><div><b>{run.title}</b><small>{run.repository} · {run.sourceRef}</small></div><time>{new Date(run.createdAt).toLocaleString()}</time></button>)}</section>{selected && <RunDetail run={selected} />}</> : <section className="not-ready"><p className="eyebrow">{activePage}</p><h1>{activePage} are policy-backed control-plane resources.</h1><p>This view will be enabled only when its persisted API and authorization rules are implemented. It will never show Ticketly-specific data.</p></section>}</div></div></main>;
}

export default App;
