package io.forgeloop.control.application;
import io.forgeloop.control.domain.*;import io.forgeloop.control.security.OperatorContext;import java.util.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
/** Owns organization-wide execution limits and reusable runner configuration. */
@Service public class PlatformConfigurationService{
 private final OperatorContext operators;private final OrganizationPolicyRepository policies;private final HarnessDefinitionRepository harnesses;private final LocalMcpConfigurationRepository mcp;private final AuditLedgerService audit;
 public PlatformConfigurationService(OperatorContext operators,OrganizationPolicyRepository policies,HarnessDefinitionRepository harnesses,LocalMcpConfigurationRepository mcp,AuditLedgerService audit){this.operators=operators;this.policies=policies;this.harnesses=harnesses;this.mcp=mcp;this.audit=audit;}
 public OrganizationPolicy policy(){return policies.findById(operators.organizationId()).orElseThrow(()->new IllegalStateException("Organization policy is not configured"));}
 @Transactional public OrganizationPolicy configurePolicy(double budget,int parallel,List<String> providers,boolean approval){operators.requireAdministrator();OrganizationPolicy value=policies.findById(operators.organizationId()).orElse(null);if(value==null)value=new OrganizationPolicy(operators.organizationId(),budget,parallel,providers,approval);else value.update(budget,parallel,providers,approval);OrganizationPolicy saved=policies.save(value);audit.record("ORGANIZATION_POLICY_UPDATED","ORGANIZATION",operators.organizationId(),"revision="+saved.getRevision());return saved;}
 public List<HarnessDefinition> harnesses(){return harnesses.findByOrganizationIdOrderByNameAsc(operators.organizationId());}
 public HarnessDefinition requireHarness(String name){HarnessDefinition value=harnesses.findByOrganizationIdAndName(operators.organizationId(),name).orElseThrow(()->new IllegalStateException("Harness definition is unavailable"));if(!value.isEnabled())throw new IllegalStateException("Harness definition is disabled");return value;}
 @Transactional public HarnessDefinition createHarness(String name,String description,List<String> roles,int attempts){operators.requireAdministrator();if(harnesses.findByOrganizationIdAndName(operators.organizationId(),name).isPresent())throw new IllegalStateException("Harness definition already exists");HarnessDefinition saved=harnesses.save(new HarnessDefinition(operators.organizationId(),name,description,roles,attempts));audit.record("HARNESS_DEFINITION_CREATED","ORGANIZATION",operators.organizationId(),name);return saved;}
 public List<LocalMcpConfiguration> mcpConfigurations(){return mcp.findByOrganizationIdOrderByNameAsc(operators.organizationId());}
 public List<LocalMcpConfiguration> taskMcp(String org,String role){return mcp.findByOrganizationIdAndEnabledTrueOrderByNameAsc(org).stream().filter(c->c.allows(role)).toList();}
 @Transactional public LocalMcpConfiguration createMcp(String name,String command,List<String> args,List<String> roles,String tool,String toolArgs){operators.requireAdministrator();LocalMcpConfiguration saved=mcp.save(new LocalMcpConfiguration(operators.organizationId(),name,command,args,roles,tool,toolArgs));audit.record("LOCAL_MCP_CONFIGURATION_CREATED","ORGANIZATION",operators.organizationId(),name);return saved;}
}
