package io.forgeloop.control.application;
import io.forgeloop.control.domain.*;
import java.util.*;
import org.springframework.stereotype.Service;
/** Computes tenant-filtered analytics from persisted run and provider telemetry. */
@Service public class RunAnalyticsService {
 private final FeatureRunService runs; public RunAnalyticsService(FeatureRunService runs){this.runs=runs;}
 public RunAnalytics snapshot(){List<FeatureRun> visible=runs.list();List<ProviderAttempt> attempts=visible.stream().flatMap(r->r.getTasks().stream()).flatMap(t->t.getProviderAttempts().stream()).toList();long known=attempts.stream().filter(ProviderAttempt::isCostKnown).count();return new RunAnalytics(visible.size(),visible.stream().filter(r->!terminal(r.getState())).count(),visible.stream().filter(r->r.getState()==RunState.COMPLETE||r.getState()==RunState.PR_OPEN).count(),attempts.size(),attempts.stream().mapToLong(ProviderAttempt::getInputTokens).sum(),attempts.stream().mapToLong(ProviderAttempt::getOutputTokens).sum(),attempts.stream().filter(ProviderAttempt::isCostKnown).mapToLong(ProviderAttempt::getEstimatedCostMicros).sum(),attempts.isEmpty()?1d:(double)known/attempts.size(),compare(visible,true),compare(visible,false));}
 private static List<RunComparison> compare(List<FeatureRun> runs,boolean model){Map<String,Set<FeatureRun>> groups=new TreeMap<>();for(FeatureRun run:runs){if(!model)groups.computeIfAbsent(run.getHarnessProfile(),x->new LinkedHashSet<>()).add(run);else for(ProviderAttempt attempt:attempts(run))groups.computeIfAbsent(attempt.getProvider()+"/"+attempt.getModel(),x->new LinkedHashSet<>()).add(run);}return groups.entrySet().stream().map(e->{List<ProviderAttempt> attempts=e.getValue().stream().flatMap(r->attempts(r).stream()).filter(a->!model||(a.getProvider()+"/"+a.getModel()).equals(e.getKey())).toList();return new RunComparison(model?"MODEL":"HARNESS",e.getKey(),e.getValue().size(),attempts.size(),attempts.stream().filter(a->"SUCCEEDED".equals(a.getOutcome())).count(),attempts.stream().mapToLong(ProviderAttempt::getInputTokens).sum(),attempts.stream().mapToLong(ProviderAttempt::getOutputTokens).sum(),attempts.stream().filter(ProviderAttempt::isCostKnown).mapToLong(ProviderAttempt::getEstimatedCostMicros).sum());}).toList();}
 private static List<ProviderAttempt> attempts(FeatureRun run){return run.getTasks().stream().flatMap(t->t.getProviderAttempts().stream()).toList();}
 private static boolean terminal(RunState s){return List.of(RunState.COMPLETE,RunState.CANCELLED,RunState.FAILED,RunState.REJECTED).contains(s);}
 public record RunAnalytics(long totalRuns,long activeRuns,long deliveredRuns,long providerRequests,long inputTokens,long outputTokens,long knownCostMicros,double costCoverage,List<RunComparison> modelComparisons,List<RunComparison> harnessComparisons){}
 public record RunComparison(String dimension,String name,long runCount,long requestCount,long successfulRequests,long inputTokens,long outputTokens,long knownCostMicros){}
}
