import {aboutGuide, featuresGuide, setupGuide, workflowGuide} from './guides';

export const SITE = 'https://forgeloop.hookerhillstudios.com';
export const REPOSITORY = 'https://github.com/JRH89/ForgeLoop';
export const PUBLISHED = '2026-09-26';
export type Section = { heading: string; body: string; points?: string[]; links?: {label:string;href:string}[] };
export type PublicPage = { path: string; title: string; description: string; eyebrow: string; heading: string; intro: string; sections: Section[] };
export const pages: PublicPage[] = [
  {path:'/',title:'ForgeLoop | Evidence-backed AI software delivery',description:'Turn GitHub issues into evidence-backed pull requests. Coordinate coding agents, verify changes, and run delivery on infrastructure you control.',eyebrow:'Autonomous software delivery',heading:'Turn GitHub issues into evidence-backed pull requests.',intro:'',sections:[]},
  {path:'/features',title:'AI coding agent orchestration features | ForgeLoop',description:'Explore GitHub intake, self-hosted runners, verification gates, repair loops, cost telemetry, and guarded pull request delivery in ForgeLoop.',eyebrow:'Built around the work',heading:'More than an agent with a terminal.',intro:'A delivery system needs to know what work is allowed, what passed, what failed, and which exact commit is ready for review.',sections:featuresGuide},
  {path:'/about',title:'About ForgeLoop | The system around coding agents',description:'Learn why ForgeLoop separates coding agents from delivery policy, verification, and evidence, with repository-agnostic runners you control.',eyebrow:'Why ForgeLoop exists',heading:'The hard part is not generating a diff.',intro:'It is making a change you can explain, verify, review, and safely integrate. ForgeLoop is built around that responsibility.',sections:aboutGuide},
  {path:'/how-it-works',title:'From GitHub issue to verified PR | ForgeLoop',description:'Follow the ForgeLoop delivery loop: intake, planning, runner execution, verification, repair, review, and guarded pull request delivery.',eyebrow:'The delivery loop',heading:'One issue. A traceable path to a pull request.',intro:'Every stage should have a clear input, a bounded action, and a result the next stage can trust.',sections:workflowGuide},
  {path:'/security',title:'Runner security and delivery boundaries | ForgeLoop',description:'Understand ForgeLoop trust boundaries: GitHub authorization, local provider keys, self-hosted execution, evidence, and guarded delivery.',eyebrow:'Explicit trust boundaries',heading:'Control what can run. Inspect what did.',intro:'Self-hosting gives you control, not immunity from risk. Treat repository content, agent output, and execution environments as separate trust boundaries.',sections:[
    {heading:'Identity is not repository permission',body:'GitHub sign-in establishes operator identity; organization membership determines roles. A GitHub App installation authorizes selected repositories. Runner enrollment grants a separate credential for runner operations. None of these steps substitutes for the others.'},
    {heading:'Keys stay with the runner',body:'Desktop provider credentials use Windows DPAPI, macOS Keychain, or Linux Secret Service. Blank password fields do not mean saved keys disappeared. The desktop can check key storage without contacting a provider; actual model requests can send repository context to the selected provider.'},
    {heading:'Execution requires a trusted host',body:'A runner can access source, local tools, and configured container capabilities. Git worktrees isolate checkout changes, not operating-system privileges. Docker daemon access is powerful: use dedicated hosts and narrow permissions, and review repository commands before enabling unattended execution.'},
    {heading:'Evidence still needs responsible handling',body:'The control plane stores run metadata and evidence, rather than serving as a repository checkout. Artifacts, issue text, or logs may contain sensitive project information. Review retention, access, and redaction requirements for your deployment. No SOC 2, compliance certification, or universal security guarantee is claimed.'},
    {heading:'Report problems responsibly',body:'Do not publish tokens, private repository contents, or exploitable vulnerability details in a public issue. Use the repository security reporting route if enabled, or establish a private channel with the maintainer before sharing sensitive details.'}
  ]},
  {path:'/docs',title:'Get started with ForgeLoop | Runner and GitHub setup',description:'Learn the ForgeLoop setup sequence: GitHub sign-in, repository authorization, runner enrollment, local provider keys, and verification policy.',eyebrow:'Start with the boundaries',heading:'Connect a repository. Bring your runner.',intro:'The website is the control plane. The runner is where repository work happens. Keep those two roles clear during setup.',sections:setupGuide},
  {path:'/blog',title:'AI software delivery field notes | ForgeLoop Blog',description:'Practical guides to coding agents, GitHub automation, self-hosted runners, verification gates, repair loops, and accountable AI delivery.',eyebrow:'Field notes',heading:'Better systems around coding agents.',intro:'Practical engineering notes for teams moving from generated code to verifiable software delivery. No invented benchmarks. No shortcut around review.',sections:[]},
  {path:'/contact',title:'Contact and project support | ForgeLoop',description:'Get ForgeLoop support, report bugs, and ask account questions. Submit with or without an account and track replies securely with a private ticket link.',eyebrow:'Build with us',heading:'Bring a reproducible problem.',intro:'Good feedback includes the expected behavior, the actual result, and enough context to reproduce it without exposing credentials.',sections:[
    {heading:'Bugs and feature requests',body:'Use the project issue tracker for non-sensitive bug reports and feature proposals. Include your operating system, installation version, reproduction steps, and a sanitized description of the result. The desktop diagnostics export deliberately leaves out keys, credentials, and raw task logs.'},
    {heading:'Questions about operating ForgeLoop',body:'Start with the public setup overview and the in-console User guide. Include whether the problem happens in the browser, control plane, GitHub integration, or local runner. A passing key-storage check does not confirm provider billing or API access.'},
    {heading:'Security and private information',body:'Do not paste API keys, installation credentials, private issue contents, or raw database exports into public discussions. Check the repository security reporting options before sending a vulnerability report. Support response times are not guaranteed.'}
  ]}
];
