export const SITE = 'https://forgeloop.hookerhillstudios.com';
export const REPOSITORY = 'https://github.com/JRH89/ForgeLoop';
export const PUBLISHED = '2026-09-26';
export type Section = { heading: string; body: string; points?: string[] };
export type PublicPage = { path: string; title: string; description: string; eyebrow: string; heading: string; intro: string; sections: Section[] };
export const pages: PublicPage[] = [
  {path:'/',title:'ForgeLoop | Evidence-backed AI software delivery',description:'Turn GitHub issues into evidence-backed pull requests. Coordinate coding agents, verify changes, and run delivery on infrastructure you control.',eyebrow:'Autonomous software delivery',heading:'Turn GitHub issues into evidence-backed pull requests.',intro:'',sections:[]},
  {path:'/features',title:'AI coding agent orchestration features | ForgeLoop',description:'Explore GitHub intake, self-hosted runners, verification gates, repair loops, cost telemetry, and guarded pull request delivery in ForgeLoop.',eyebrow:'Built around the work',heading:'More than an agent with a terminal.',intro:'A delivery system needs to know what work is allowed, what passed, what failed, and which exact commit is ready for review.',sections:[
    {heading:'From issue to bounded task graph',body:'Connect an authorized GitHub repository, define intake policy, and turn a specification into work with dependencies, acceptance criteria, and ownership boundaries.',points:['Label and assignment-based issue intake','Task leases and isolated Git worktrees','Reusable harness definitions and organization policies']},
    {heading:'Verification that produces evidence',body:'Verification is a stage of delivery, not a sentence in a model response. Inspect criterion coverage, checksummed artifacts, test output, and screenshot evidence when a configured browser gate produces it.',points:['Policy-selected verification commands','Bounded repair loops and human escalation','Independent review before guarded delivery']},
    {heading:'Your execution environment',body:'ForgeLoop coordinates work from a web control plane. Enrolled runners execute repository work on your infrastructure and use locally configured provider credentials.',points:['Windows, macOS, and Linux desktop preview builds','Runner-local provider keys and MCP processes','Explicit start, graceful pause, and optional login startup']},
    {heading:'An operator view of delivery',body:'Follow run progress, review events and artifacts, inspect provider usage, and decide when delivery should proceed. Cost estimates require model prices; missing pricing is shown as unavailable rather than zero.',points:['Run archive and lifecycle controls','Provider telemetry and estimated costs','Human approval or explicitly enabled guarded auto-merge']}
  ]},
  {path:'/about',title:'About ForgeLoop | The system around coding agents',description:'Learn why ForgeLoop separates coding agents from delivery policy, verification, and evidence, with repository-agnostic runners you control.',eyebrow:'Why ForgeLoop exists',heading:'The hard part is not generating a diff.',intro:'It is making a change you can explain, verify, review, and safely integrate. ForgeLoop is built around that responsibility.',sections:[
    {heading:'A delivery harness, not another issue tracker',body:'GitHub issues describe the work. Coding agents propose changes. ForgeLoop coordinates the steps between them: planning, execution, integration, verification, repair, review, and delivery. The dashboard exists to make that process inspectable, not to replace your repository workflow.'},
    {heading:'Repository agnostic by design',body:'Connect your own GitHub repositories without moving application code into ForgeLoop. Each repository keeps its own stack, history, and verification commands, while repository policy defines how work is authorized and checked.'},
    {heading:'Built by Hooker Hill Studios',body:'ForgeLoop is a Hooker Hill Studios project. Its source, implementation notes, and progress checklist are available on GitHub. The goal is a maintainable delivery system with explicit boundaries, not an unsupported promise that every task can run without human judgment.'},
    {heading:'Evidence before claims',body:'A passing local test is not the same as a validated production rollout. Native desktop builds and offline checks are available as development previews; signed public distribution and additional real-world delivery validation have separate release gates. Read the current checklist before choosing an installation path.'}
  ]},
  {path:'/how-it-works',title:'From GitHub issue to verified PR | ForgeLoop',description:'Follow the ForgeLoop delivery loop: intake, planning, runner execution, verification, repair, review, and guarded pull request delivery.',eyebrow:'The delivery loop',heading:'One issue. A traceable path to a pull request.',intro:'Every stage should have a clear input, a bounded action, and a result the next stage can trust.',sections:[
    {heading:'01 / Authorize and receive',body:'Install the GitHub App on selected repositories and configure intake rules. Assignment-gated intake lets you decide when an issue becomes eligible. User-submitted work still belongs to an authorized repository and an organization policy.'},
    {heading:'02 / Plan and execute',body:'A validated plan divides work into tasks with dependencies and owned paths. An enrolled runner claims leased work, prepares an isolated worktree, and executes the configured agent or verification operation. Provider calls happen on the runner using its local credentials.'},
    {heading:'03 / Verify and repair',body:'Run the configured gates against the relevant commit. Failed work can enter a bounded repair cycle with failure context. Exhausted limits and ambiguous situations should escalate to a person instead of silently claiming success.'},
    {heading:'04 / Review and deliver',body:'Review evidence, acceptance coverage, and the proposed change. Delivery and optional auto-merge are guarded operations tied to the expected commit. A new commit is a new verification question, not permission to reuse stale green checks.'}
  ]},
  {path:'/security',title:'Runner security and delivery boundaries | ForgeLoop',description:'Understand ForgeLoop trust boundaries: GitHub authorization, local provider keys, self-hosted execution, evidence, and guarded delivery.',eyebrow:'Explicit trust boundaries',heading:'Control what can run. Inspect what did.',intro:'Self-hosting gives you control, not immunity from risk. Treat repository content, agent output, and execution environments as separate trust boundaries.',sections:[
    {heading:'Identity is not repository permission',body:'GitHub sign-in establishes operator identity; organization membership determines roles. A GitHub App installation authorizes selected repositories. Runner enrollment grants a separate credential for runner operations. None of these steps substitutes for the others.'},
    {heading:'Keys stay with the runner',body:'Desktop provider credentials use Windows DPAPI, macOS Keychain, or Linux Secret Service. Blank password fields do not mean saved keys disappeared. The desktop can check key storage without contacting a provider; actual model requests can send repository context to the selected provider.'},
    {heading:'Execution requires a trusted host',body:'A runner can access source, local tools, and configured container capabilities. Git worktrees isolate checkout changes, not operating-system privileges. Docker daemon access is powerful: use dedicated hosts and narrow permissions, and review repository commands before enabling unattended execution.'},
    {heading:'Evidence still needs responsible handling',body:'The control plane stores run metadata and evidence, rather than serving as a repository checkout. Artifacts, issue text, or logs may contain sensitive project information. Review retention, access, and redaction requirements for your deployment. No SOC 2, compliance certification, or universal security guarantee is claimed.'},
    {heading:'Report problems responsibly',body:'Do not publish tokens, private repository contents, or exploitable vulnerability details in a public issue. Use the repository security reporting route if enabled, or establish a private channel with the maintainer before sharing sensitive details.'}
  ]},
  {path:'/docs',title:'Get started with ForgeLoop | Runner and GitHub setup',description:'Learn the ForgeLoop setup sequence: GitHub sign-in, repository authorization, runner enrollment, local provider keys, and verification policy.',eyebrow:'Start with the boundaries',heading:'Connect a repository. Bring your runner.',intro:'The website is the control plane. The runner is where repository work happens. Keep those two roles clear during setup.',sections:[
    {heading:'1 / Sign in and authorize a repository',body:'Sign in with GitHub using an account invited to the deployment. Install the ForgeLoop GitHub App for the repositories you want it to access. Set intake rules before submitting or assigning work.'},
    {heading:'2 / Choose an installation path',body:'Choose Download runner in the footer for the latest desktop preview from GitHub Releases. Installers bundle Java and use browser approval. Windows x64, macOS Apple Silicon and Intel, and Debian/Ubuntu Linux x64 packages are available. Previews are unsigned; Windows and macOS may show publisher warnings. Optional SHA-256 checksums accompany each download.'},
    {heading:'3 / Pair and save a provider key',body:'For the desktop preview, choose Connect in browser, compare fingerprints, and approve as an organization administrator. Save your provider key locally. Reopening a configured app selects Run; leave the key field blank to keep the saved credential.'},
    {heading:'4 / Check without spending',body:'Check Git and Docker, check the saved connection, and check the saved key locally. These checks do not call a model. Keep Start work at sign-in off until you intend to process eligible work. Start runner is not a dry-run button.'},
    {heading:'5 / Configure verification and start deliberately',body:'Select model pricing, task limits, repository verification commands, and approval policy before starting. Read User guide in the console for the full settings reference, troubleshooting, and operating procedures. Pause drains current work; it does not undo already incurred charges.'}
  ]},
  {path:'/blog',title:'AI software delivery field notes | ForgeLoop Blog',description:'Practical guides to coding agents, GitHub automation, self-hosted runners, verification gates, repair loops, and accountable AI delivery.',eyebrow:'Field notes',heading:'Better systems around coding agents.',intro:'Practical engineering notes for teams moving from generated code to verifiable software delivery. No invented benchmarks. No shortcut around review.',sections:[]},
  {path:'/contact',title:'Contact and project support | ForgeLoop',description:'Get ForgeLoop support, report bugs, and ask account questions. Submit with or without an account and track replies securely with a private ticket link.',eyebrow:'Build with us',heading:'Bring a reproducible problem.',intro:'Good feedback includes the expected behavior, the actual result, and enough context to reproduce it without exposing credentials.',sections:[
    {heading:'Bugs and feature requests',body:'Use the project issue tracker for non-sensitive bug reports and feature proposals. Include your operating system, installation version, reproduction steps, and a sanitized description of the result. The desktop diagnostics export deliberately leaves out keys, credentials, and raw task logs.'},
    {heading:'Questions about operating ForgeLoop',body:'Start with the public setup overview and the in-console User guide. Include whether the problem happens in the browser, control plane, GitHub integration, or local runner. A passing key-storage check does not confirm provider billing or API access.'},
    {heading:'Security and private information',body:'Do not paste API keys, installation credentials, private issue contents, or raw database exports into public discussions. Check the repository security reporting options before sending a vulnerability report. Support response times are not guaranteed.'}
  ]}
];
