import type {Section} from './content';

export const featuresGuide: Section[] = [
  {heading:'GitHub intake you control',body:'Turn an issue into eligible work using the repository rules you choose. Connect selected repositories through the GitHub App, then configure the intake label and optional assignment gate. Choose any GitHub assignee or one exact login. Safe issue drafts prefill the title and acceptance-criteria body without attaching activation metadata; add the missing label or assignment only when ready.',points:['Keep issues and pull requests in your existing GitHub workflow.','Require assignment when you want an explicit handoff before processing.','Paste an issue number or matching GitHub issue URL into the read-only intake diagnostic; it checks rules without editing or starting work.','Keep your runner stopped until eligible issues are intentionally allowed to start provider work.'],links:[{label:'Connect your first repository',href:'/docs#connect-github-and-select-a-repository'}]},
  {heading:'Plans with clear task boundaries',body:'ForgeLoop turns a specification into a task graph with dependencies, acceptance criteria, and owned paths. Agents work on defined units of the change, while the orchestration tracks what must finish before another task can proceed.',points:['Independent work can proceed when dependencies permit.','Leases track which runner has claimed a task.','Isolated Git worktrees separate checkout changes during execution.','Acceptance criteria keep the plan connected to the behavior the issue requested.'],links:[{label:'Follow a run through its stages',href:'/how-it-works'}]},
  {heading:'Reusable repository harnesses',body:'A harness describes how to work with a repository and verify its changes. Connect your existing stack and configure the commands and gates it needs, rather than moving application code into ForgeLoop or adopting a special example project.',points:['Reuse harness definitions across repositories with similar requirements.','Choose verification commands appropriate to the repository, such as tests and builds.','Organization policies define execution limits and approval requirements.','Runner-local MCP processes make configured tools available where repository work executes.'],links:[{label:'Define your verification policy',href:'/docs#define-what-a-passing-change-means'}]},
  {heading:'Runners on your infrastructure',body:'The browser coordinates delivery and shows its progress. An enrolled runner executes repository commands on a computer you operate, using locally configured provider credentials. The desktop app handles pairing, provider settings, readiness checks, and starting or pausing work.',points:['The downloads page lists the platforms included in the latest complete release. The expanded matrix covers Windows x64/ARM64, macOS Apple Silicon/Intel, and Linux x64/arm64.','Linux package formats include DEB, RPM, portable tar.gz, and a native Arch pacman package; AppImage is no longer used for new releases.','Java is bundled; Git and Docker are prerequisites.','Compare the desktop and browser fingerprints when approving enrollment.','Check saved credentials locally without making a model request. Starting work can incur provider charges.'],links:[{label:'Download the runner',href:'/app/runner-downloads'},{label:'Read the execution boundaries',href:'/security'}]},
  {heading:'Verification with inspectable evidence',body:'Configured gates evaluate the change and produce results tied to the commit under review. Inspect command output, acceptance coverage, and checksummed artifacts to understand what was tested and where verification fell short.',points:['Use test and build output to evaluate results alongside the proposed diff.','Review screenshot evidence when a configured browser gate produces it.','Choose checks that exercise both expected behavior and failure paths.','Passing repository checks supports review; deployment validation remains part of your application release process.']},
  {heading:'Bounded repair and review',body:'A failed verification step can send failure context into a repair loop. ForgeLoop tracks the attempts within configured limits so the next action is informed by the failed check. When limits are exhausted, the run needs attention rather than an unsupported success claim.',points:['Inspect failing gates and repair attempts in run details.','Set task and budget limits before starting eligible work.','Independent review adds another stage before guarded delivery.','Use the recorded failure context to decide whether to revise the issue, adjust a command, or intervene.'],links:[{label:'Understand the repair stage',href:'/how-it-works#repair-failures-within-limits'}]},
  {heading:'Pull requests and optional auto-merge',body:'Delivery brings the proposed change back to your repository as a pull request, with review and verification evidence supporting the decision. Human approval and optional auto-merge follow the configured policy and checks for the expected commit.',points:['Keep human approval where your workflow requires it.','Explicitly enable auto-merge when you want eligible changes merged after its checks pass.','A new commit must satisfy delivery checks; an earlier passing result does not authorize a changed branch.','Continue using your normal deployment and release process after merge.']},
  {heading:'Run visibility and estimated spending',body:'Follow runs from the console, inspect their tasks and events, and open artifacts when you need detail. Usage & costs brings recorded provider usage into daily spending views and model breakdowns, helping you understand where work is consuming tokens.',points:['Filter usage by repository and the last 7, 30, or 90 UTC calendar days.','Inspect token usage, estimated costs, and pricing coverage. Missing prices appear as unavailable, not as zero cost.','The runner looks up public base model prices automatically; you can override account-specific rates. Totals are estimates, not a provider invoice or account balance.','Archive finished runs to clear the queue while retaining their contribution to usage totals.'],links:[{label:'Read setup and operating guidance',href:'/docs'},{label:'Open the console',href:'/app'}]}
];

// Public guidance stays readable without an account; account controls remain in the console.
export const setupGuide: Section[] = [
  {heading:'Before you begin',body:'You need a GitHub account with access to the deployment, a repository you can authorize, and a computer that can run Git and Docker. The browser coordinates delivery; your enrolled runner performs the repository work.',points:['The downloads page shows the assets present in the latest complete release. The supported desktop targets are Windows x64/ARM64, macOS Apple Silicon/Intel, and Linux x64/arm64. Linux formats include DEB, RPM, portable tar.gz, and Arch pacman packages.','Install Git and Docker, then start Docker before checking runner readiness.','Have a supported model provider API key ready. Provider usage is billed by that provider; installing the runner does not add API credit.'],links:[{label:'Download the runner',href:'/app/runner-downloads'},{label:'Understand runner permissions',href:'/security'}]},
  {heading:'Connect GitHub and select a repository',body:'Sign in with GitHub, open Repositories, and install the ForgeLoop GitHub App for the repositories you want to use. Signing in identifies you; installing the App grants repository access. Complete both steps and confirm the repository appears in the console.',points:['Choose the intended base branch and repository harness. Keep your existing language, framework, and Git history.','Set the intake label and, if you want work to wait for assignment, enable the gate. Leave the login blank to accept anyone GitHub assigns or enter one exact login. An issue must satisfy the configured intake rules.','If a repository is missing, check the App installation’s selected repositories and your organization access.'],links:[{label:'Open the console',href:'/app'}]},
  {heading:'Install and pair your runner',body:'Download the package for your operating system, install it, and open ForgeLoop Runner. In Connect, use Connect in browser. Compare the fingerprint in the desktop app with the browser approval page, then approve using an organization administrator account.',points:['Return to the desktop app to finish connecting. The browser approval alone does not start work.','Use Check saved connection to verify enrollment. Reopening a configured app takes you to Run.','The current installers are unsigned previews. The download page includes version information, platform details, and optional SHA-256 verification.'],links:[{label:'Get the latest installer',href:'/app/runner-downloads'}]},
  {heading:'Configure your provider and estimated prices',body:'In Provider, choose your provider and model, enter its API key, and save. Credentials are stored on the runner using the operating system’s credential protection. A blank key field after reopening keeps the saved credential; it does not mean the key was lost.',points:['Check saved key locally verifies storage without making a model request. It does not confirm provider credit or model access.','Public base token prices are looked up automatically. You can override account-specific rates; unknown pricing appears as N/A, and estimated spending is not a provider invoice.','Saving settings does not start a paid task. Starting the runner can claim eligible work and make paid requests.']},
  {heading:'Define what a passing change means',body:'Before starting work, review the repository’s verification commands and Harness & policy settings. A harness tells ForgeLoop how to work with and check a repository. Choose commands that can prove the behavior you care about, including failure paths.',points:['Set task and budget limits appropriate to the change. Include test, build, and other required gates for your repository.','Decide whether delivery needs human approval. Enable auto-merge only when you want eligible changes merged after its checks pass.','Keep the runner stopped while preparing an issue if you are not ready to incur provider charges.']},
  {heading:'Submit a small first issue',body:'Start with one change you can review. Describe the current behavior, the expected behavior, the files or feature area involved, and observable acceptance criteria. Apply the configured label and assignee when you are ready for intake.',points:['Example: “Show an empty state when search returns no results. Keep the search input and filters visible. Add a test for zero results and preserve existing loading and error states.”','Avoid open-ended requests such as “improve the whole app.” State what is outside the requested change.','Follow the run in Runs. Open its details to inspect tasks, events, verification output, and delivery progress.'],links:[{label:'Follow the delivery stages',href:'/how-it-works'}]},
  {heading:'Review, pause, and update',body:'Review the proposed diff alongside its acceptance coverage and verification evidence. A completed run does not replace your deployment process. After delivery, use your normal release checks for the target application.',points:['Pause after current work lets active work finish before the runner claims more. It does not reverse charges already incurred.','To update: pause, wait for work to finish, close the app, install the newer package, and reopen. Saved identity and provider settings live outside the installation directory.','Use Usage & costs to inspect estimated spending and pricing coverage. Archive finished runs to tidy the queue; archived runs remain included in usage totals.']},
  {heading:'When a run does not start',body:'Open Getting started in the console to check repository setup and diagnose intake. Work can be waiting for authorization, an intake rule, an available runner, or a policy decision. Check the relevant stage before resubmitting the same issue.',points:['Repository missing: review GitHub App access and your organization membership.','Issue waiting: check the exact label and required assignee, then inspect intake diagnostics.','Runner offline: reopen the app, check the saved connection, and confirm Git and Docker readiness.','Provider failure: check the chosen model, API access, and provider billing. A local key-storage check cannot verify those.'],links:[{label:'Open the console for User guide',href:'/app'},{label:'Ask for support',href:'/contact'}]}
];

export const workflowGuide: Section[] = [
  {heading:'Authorize the work',body:'A connected repository and its intake policy define which issues can become runs. You can require a label and assignment before processing begins, or submit work through the console for an authorized repository.',points:['Your input: a bounded issue with acceptance criteria.','Your control: repository access, intake rules, and organization policy.','Visible result: a run you can follow in the console.']},
  {heading:'Turn the specification into a plan',body:'ForgeLoop organizes the requested change into tasks with dependencies and file ownership boundaries. This gives agents a defined area of work and tells the system which tasks must finish before others can proceed.',points:['Independent tasks can proceed when their dependencies permit.','The plan connects implementation work to the acceptance criteria.','A vague specification still needs clarification; orchestration cannot supply missing product decisions.']},
  {heading:'Execute on your runner',body:'An enrolled runner claims available work through a lease and prepares an isolated Git worktree. Agents use repository context, configured tools, and the selected provider to make changes on your infrastructure.',points:['The web control plane records and coordinates delivery. The runner executes repository commands.','Provider keys are configured locally. Model requests can send repository context to the selected provider.','Worktrees separate checkout changes; they are not a security sandbox for arbitrary commands.'],links:[{label:'Explore execution boundaries',href:'/security'}]},
  {heading:'Integrate and verify the change',body:'The proposed changes must pass the configured verification gates. Tests, builds, and other commands produce evidence for the commit being evaluated. Browser screenshots are available when a configured browser gate produces them.',points:['Inspect command output and artifacts, rather than relying only on an agent’s summary.','Acceptance coverage helps connect the specification to what was checked.','The quality of the result depends on the quality of your verification commands and criteria.']},
  {heading:'Repair failures within limits',body:'When verification fails, the failure context can feed a bounded repair loop. The aim is to correct the failing change and verify it again. Limits keep unsuccessful work from continuing indefinitely.',points:['Review failed gates and repair attempts in the run details.','A task that exhausts its limits needs attention; failure is not converted into a successful delivery.','Use clear error reports and focused acceptance criteria to make repair attempts more useful.']},
  {heading:'Review and deliver a pull request',body:'The final diff, review, and verification evidence support a pull request in your repository. Human approval and optional auto-merge follow the configured policy. Delivery is checked against the expected commit, so a changed branch cannot simply inherit an earlier passing result.',points:['Human review: inspect the diff, test results, and unresolved questions.','Optional auto-merge: explicitly enable it and satisfy its delivery checks.','After merge: deploy and validate the application through your own release process.'],links:[{label:'Set up your first run',href:'/docs'},{label:'See the feature overview',href:'/features'}]}
];

export const aboutGuide: Section[] = [
  {heading:'Why the system around the agent matters',body:'A generated change is only one part of software delivery. Someone still has to decide what work is allowed, coordinate dependent changes, run checks, interpret failures, and determine whether the result is ready to merge. ForgeLoop brings those responsibilities into an inspectable workflow.',points:['GitHub remains the place for issues, branches, and pull requests.','Agents implement bounded tasks inside that workflow.','ForgeLoop coordinates planning, execution, verification, repair, review, and delivery.']},
  {heading:'Built for your existing repositories',body:'ForgeLoop is repository agnostic. You connect your own GitHub repository and keep its stack, history, conventions, and deployment process. Repository-specific harnesses and verification commands describe how work should be performed and checked.',points:['Useful for teams experimenting with issue-to-PR automation on reviewable changes.','Useful for maintainers who want visibility into agent work and evidence before delivery.','Each repository still needs appropriate tooling and checks; connecting it does not automatically make every task suitable for automation.']},
  {heading:'A browser control plane and a runner you operate',body:'The website provides the operator view: repositories, runs, policies, evidence, and usage. Your enrolled runner executes repository work and uses locally configured provider credentials. This separation gives you a clear place to inspect delivery and a clear place to control execution.',points:['Start and pause work from the desktop runner.','Choose provider settings and keep credentials on the runner.','Inspect progress and estimated usage through the console.'],links:[{label:'Read the setup guide',href:'/docs'},{label:'Understand security boundaries',href:'/security'}]},
  {heading:'Evidence is part of the product',body:'ForgeLoop is built around results that can be inspected: verification output, acceptance coverage, artifacts, and the commit associated with delivery. Those records make it easier to understand why a change passed, why it failed, and where a person needs to intervene.',points:['A model’s explanation is useful context, but does not substitute for a passing check.','Estimated costs depend on configured pricing and recorded usage.','Passing repository checks does not prove a production deployment will succeed.']},
  {heading:'Where the project stands',body:'Desktop previews are available for Windows, macOS, and Linux; the downloads page only lists assets from a complete published release. The expanded matrix covers Windows x64/ARM64, macOS Apple Silicon/Intel, and Linux x64/arm64 DEB, RPM, portable tar.gz, and native Arch packages. Previews are unsigned, and macOS packages are not notarized. Published downloads include version information and checksums.',points:['Use the current release notes and repository checklist to assess readiness for your environment.','Begin with a small issue, explicit limits, and reviewable acceptance criteria.','Report reproducible problems through support without including credentials or private source.'],links:[{label:'View current downloads',href:'/app/runner-downloads'},{label:'See the delivery workflow',href:'/how-it-works'}]}
];
