import LandingPage from '../LandingPage';
import MarkdownContent from '../MarkdownContent';
import { articles } from './articles';
import { pages, REPOSITORY } from './content';
import { PublicLayout, PublicHero } from './PublicLayout';
import { ArticleCards } from './ArticleCards';
import './public.css';

export default function PublicSite({path}:{path:string}) {
  if(path==='/')return <LandingPage/>;
  if(path==='/support')return <PublicLayout><section className="public-section"><p className="eyebrow">Private customer support</p><h1>Support center</h1><div id="support-root"><p>Loading your support workspace…</p><noscript>Enable JavaScript to securely view and reply to tickets.</noscript></div></section></PublicLayout>;
  const article=articles.find(item=>path===`/blog/${item.slug}`);
  if(article)return <PublicLayout><PublicHero path={path} eyebrow={article.category} heading={article.title} intro={article.description}/><article className="article-body"><nav aria-label="Breadcrumb"><a href="/">Home</a> / <a href="/blog">Field notes</a> / <span>{article.title}</span></nav><p className="article-byline">By <a href="/about">Hooker Hill Studios</a> · Published <time dateTime={article.published}>September 26, 2026</time> · {Math.ceil(article.body.split(/\s+/).length/220)} min read</p><MarkdownContent content={article.body}/><aside className="article-next"><h2>Put the boundaries into practice.</h2><p>Start with repository authorization, an enrolled runner, and explicit verification policy.</p><a className="primary" href="/docs">Read the setup guide</a><a href="/blog">More field notes →</a></aside></article></PublicLayout>;
  const page=pages.find(item=>item.path===path);
  if(path==='/contact'&&page)return <PublicLayout><PublicHero path={path} eyebrow={page.eyebrow} heading={page.heading} intro={page.intro}/><section className="public-section" id="support"><div id="support-root" data-mode="contact"><h2>Send a private support request</h2><p>Submit a question, report a bug, or ask for help with your account. Include the expected behavior, actual result, your operating system, and steps to reproduce the issue. Do not include passwords, API keys, payment details, or sensitive repository contents.</p><p>You can submit without an account and save a private tracking link to read replies and check status. Signed-in users can also find their requests in My tickets. Email notifications are not enabled; use the support portal to follow your request. Response times are not guaranteed.</p><noscript>Enable JavaScript to use the secure support form.</noscript></div><p>Already contacted us? <a href="/support">Track a ticket or view My tickets</a>.</p></section></PublicLayout>;
  if(!page)return <PublicLayout><PublicHero path="/not-found" eyebrow="404 / Page not found" heading="This path does not lead to a run." intro="The page may have moved, or the address may be incomplete."/><section className="public-section"><a className="primary" href="/">Return home</a> <a href="/docs">Read the setup guide</a></section></PublicLayout>;
  const isGuide=['/docs','/about','/how-it-works'].includes(path);
  const sectionId=(heading:string)=>heading.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
  return <PublicLayout><PublicHero path={path} eyebrow={page.eyebrow} heading={page.heading} intro={page.intro}/>{path==='/blog'?<section className="public-section"><ArticleCards/></section>:<div className={`public-section ${isGuide?'guide-layout':''}`}>
    {isGuide&&<nav className="guide-toc" aria-label="On this page"><p className="eyebrow">On this page</p>{page.sections.map(section=><a key={section.heading} href={`#${sectionId(section.heading)}`}>{section.heading}</a>)}<a className="guide-download" href="/app/runner-downloads">Download runner →</a></nav>}
    <div className={`page-sections ${isGuide?'guide-sections':''}`}>{page.sections.map((section,index)=><section id={sectionId(section.heading)} key={section.heading}>{!isGuide&&<span className="section-number">{String(index+1).padStart(2,'0')}</span>}<div><h2>{section.heading}</h2><p>{section.body}</p>{section.points&&<ul>{section.points.map(point=><li key={point}>{point}</li>)}</ul>}{section.links&&<div className="guide-links">{section.links.map(link=><a key={link.href} href={link.href}>{link.label} →</a>)}</div>}</div></section>)}<div className="public-cta"><h2>Ready for your first run?</h2><p>Connect a repository, set up your runner, and start with a small change you can review.</p><div className="landing-actions"><a className="primary" href="/app/runner-downloads">Download runner</a><a className="secondary" href={REPOSITORY}>View on GitHub</a></div></div></div>
  </div>}</PublicLayout>;
}
